In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("/Users/masoomsingh/Desktop/air_quality_raw_1000.csv")
df

,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI
0,2022-01-01,NaN,108.863806,56.032608,67.924893,NaN,124.154301,30.930278,13.491951,10.943885,458.517445
1,2022-01-02,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031
2,2022-01-03,295.477637,NaN,181.719643,26.545854,3.824789,257.818744,39.895783,84.812122,1.888436,367.956930
3,2022-01-04,243.476809,NaN,53.661509,63.237662,0.854110,108.601272,29.524650,79.009152,13.877300,229.303183
4,2022-01-05,70.847270,407.149351,58.030197,58.031106,0.831322,262.198409,11.288155,41.557842,NaN,322.416597
...,...,...,...,...,...,...,...,...,...,...,...
995,2024-09-22,45.717009,335.338475,173.732673,45.326489,NaN,208.486255,28.189485,34.584366,7.966478,431.674874
996,2024-09-23,367.752294,479.175018,35.668276,NaN,0.684967,155.933920,31.681474,28.856730,2.897871,NaN
997,2024-09-24,63.359266,53.099848,65.408633,40.668087,NaN,231.893166,41.463075,50.979587,14.676836,474.419799
998,2024-09-25,380.592568,47.386266,61.558879,53.934178,4.097152,150.734284,NaN,91.759379,2.064906,NaN
999,2024-09-26,183.942251,155.449796,174.925737,17.814001,3.026831,53.320675,29.860292,19.403229,14.013190,124.227394

In [3]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         1000 non-null   object
 1   PM2.5        900 non-null    float64
 2   PM10         900 non-null    float64
 3   NO2          900 non-null    float64
 4   SO2          900 non-null    float64
 5   CO           900 non-null    float64
 6   O3           900 non-null    float64
 7   Temperature  900 non-null    float64
 8   Humidity     900 non-null    float64
 9   WindSpeed    900 non-null    float64
 10  AQI          900 non-null    float64
dtypes: float64(10), object(1)
memory usage: 86.1+ KB

Date             0
PM2.5          100
PM10           100
NO2            100
SO2            100
CO             100
O3             100
Temperature    100
Humidity       100
WindSpeed      100
AQI            100
dtype: int64

In [4]:
df.isnull().sum()

Date             0
PM2.5          100
PM10           100
NO2            100
SO2            100
CO             100
O3             100
Temperature    100
Humidity       100
WindSpeed      100
AQI            100
dtype: int64

In [6]:
df.fillna(df.mean(numeric_only=True), inplace=True)
df

,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI
0,2022-01-01,199.994633,108.863806,56.032608,67.924893,2.523095,124.154301,30.930278,13.491951,10.943885,458.517445
1,2022-01-02,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031
2,2022-01-03,295.477637,263.784526,181.719643,26.545854,3.824789,257.818744,39.895783,84.812122,1.888436,367.956930
3,2022-01-04,243.476809,263.784526,53.661509,63.237662,0.854110,108.601272,29.524650,79.009152,13.877300,229.303183
4,2022-01-05,70.847270,407.149351,58.030197,58.031106,0.831322,262.198409,11.288155,41.557842,7.550271,322.416597
...,...,...,...,...,...,...,...,...,...,...,...
995,2024-09-22,45.717009,335.338475,173.732673,45.326489,2.523095,208.486255,28.189485,34.584366,7.966478,431.674874
996,2024-09-23,367.752294,479.175018,35.668276,50.086419,0.684967,155.933920,31.681474,28.856730,2.897871,260.247033
997,2024-09-24,63.359266,53.099848,65.408633,40.668087,2.523095,231.893166,41.463075,50.979587,14.676836,474.419799
998,2024-09-25,380.592568,47.386266,61.558879,53.934178,4.097152,150.734284,24.851836,91.759379,2.064906,260.247033
999,2024-09-26,183.942251,155.449796,174.925737,17.814001,3.026831,53.320675,29.860292,19.403229,14.013190,124.227394

In [7]:
df.isnull().sum()

Date           0
PM2.5          0
PM10           0
NO2            0
SO2            0
CO             0
O3             0
Temperature    0
Humidity       0
WindSpeed      0
AQI            0
dtype: int64

In [9]:
df.drop_duplicates(inplace=True)
df

,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI
0,2022-01-01,199.994633,108.863806,56.032608,67.924893,2.523095,124.154301,30.930278,13.491951,10.943885,458.517445
1,2022-01-02,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031
2,2022-01-03,295.477637,263.784526,181.719643,26.545854,3.824789,257.818744,39.895783,84.812122,1.888436,367.956930
3,2022-01-04,243.476809,263.784526,53.661509,63.237662,0.854110,108.601272,29.524650,79.009152,13.877300,229.303183
4,2022-01-05,70.847270,407.149351,58.030197,58.031106,0.831322,262.198409,11.288155,41.557842,7.550271,322.416597
...,...,...,...,...,...,...,...,...,...,...,...
995,2024-09-22,45.717009,335.338475,173.732673,45.326489,2.523095,208.486255,28.189485,34.584366,7.966478,431.674874
996,2024-09-23,367.752294,479.175018,35.668276,50.086419,0.684967,155.933920,31.681474,28.856730,2.897871,260.247033
997,2024-09-24,63.359266,53.099848,65.408633,40.668087,2.523095,231.893166,41.463075,50.979587,14.676836,474.419799
998,2024-09-25,380.592568,47.386266,61.558879,53.934178,4.097152,150.734284,24.851836,91.759379,2.064906,260.247033
999,2024-09-26,183.942251,155.449796,174.925737,17.814001,3.026831,53.320675,29.860292,19.403229,14.013190,124.227394

In [10]:
df['Date'] = pd.to_datetime(df['Date'])
df

,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI
0,2022-01-01,199.994633,108.863806,56.032608,67.924893,2.523095,124.154301,30.930278,13.491951,10.943885,458.517445
1,2022-01-02,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031
2,2022-01-03,295.477637,263.784526,181.719643,26.545854,3.824789,257.818744,39.895783,84.812122,1.888436,367.956930
3,2022-01-04,243.476809,263.784526,53.661509,63.237662,0.854110,108.601272,29.524650,79.009152,13.877300,229.303183
4,2022-01-05,70.847270,407.149351,58.030197,58.031106,0.831322,262.198409,11.288155,41.557842,7.550271,322.416597
...,...,...,...,...,...,...,...,...,...,...,...
995,2024-09-22,45.717009,335.338475,173.732673,45.326489,2.523095,208.486255,28.189485,34.584366,7.966478,431.674874
996,2024-09-23,367.752294,479.175018,35.668276,50.086419,0.684967,155.933920,31.681474,28.856730,2.897871,260.247033
997,2024-09-24,63.359266,53.099848,65.408633,40.668087,2.523095,231.893166,41.463075,50.979587,14.676836,474.419799
998,2024-09-25,380.592568,47.386266,61.558879,53.934178,4.097152,150.734284,24.851836,91.759379,2.064906,260.247033
999,2024-09-26,183.942251,155.449796,174.925737,17.814001,3.026831,53.320675,29.860292,19.403229,14.013190,124.227394

In [12]:
df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month
df['day'] = df['Date'].dt.day
df

,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI,year,month,day
0,2022-01-01,199.994633,108.863806,56.032608,67.924893,2.523095,124.154301,30.930278,13.491951,10.943885,458.517445,2022,1,1
1,2022-01-02,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031,2022,1,2
2,2022-01-03,295.477637,263.784526,181.719643,26.545854,3.824789,257.818744,39.895783,84.812122,1.888436,367.956930,2022,1,3
3,2022-01-04,243.476809,263.784526,53.661509,63.237662,0.854110,108.601272,29.524650,79.009152,13.877300,229.303183,2022,1,4
4,2022-01-05,70.847270,407.149351,58.030197,58.031106,0.831322,262.198409,11.288155,41.557842,7.550271,322.416597,2022,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2024-09-22,45.717009,335.338475,173.732673,45.326489,2.523095,208.486255,28.189485,34.584366,7.966478,431.674874,2024,9,22
996,2024-09-23,367.752294,479.175018,35.668276,50.086419,0.684967,155.933920,31.681474,28.856730,2.897871,260.247033,2024,9,23
997,2024-09-24,63.359266,53.099848,65.408633,40.668087,2.523095,231.893166,41.463075,50.979587,14.676836,474.419799,2024,9,24
998,2024-09-25,380.592568,47.386266,61.558879,53.934178,4.097152,150.734284,24.851836,91.759379,2.064906,260.247033,2024,9,25
999,2024-09-26,183.942251,155.449796,174.925737,17.814001,3.026831,53.320675,29.860292,19.403229,14.013190,124.227394,2024,9,26

In [17]:
df.columns

Index(['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3', 'Temperature', 'Humidity',
       'WindSpeed', 'AQI', 'year', 'month', 'day'],
      dtype='object')

In [19]:
df.reset_index(inplace=True)

In [23]:
print(df.columns)
df

Index(['level_0', 'index', 'PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3',
       'Temperature', 'Humidity', 'WindSpeed', 'AQI', 'year', 'month', 'day'],
      dtype='object')

,level_0,index,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI,year,month,day
0,0,0,199.994633,108.863806,56.032608,67.924893,2.523095,124.154301,30.930278,13.491951,10.943885,458.517445,2022,1,1
1,1,1,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031,2022,1,2
2,2,2,295.477637,263.784526,181.719643,26.545854,3.824789,257.818744,39.895783,84.812122,1.888436,367.956930,2022,1,3
3,3,3,243.476809,263.784526,53.661509,63.237662,0.854110,108.601272,29.524650,79.009152,13.877300,229.303183,2022,1,4
4,4,4,70.847270,407.149351,58.030197,58.031106,0.831322,262.198409,11.288155,41.557842,7.550271,322.416597,2022,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,995,45.717009,335.338475,173.732673,45.326489,2.523095,208.486255,28.189485,34.584366,7.966478,431.674874,2024,9,22
996,996,996,367.752294,479.175018,35.668276,50.086419,0.684967,155.933920,31.681474,28.856730,2.897871,260.247033,2024,9,23
997,997,997,63.359266,53.099848,65.408633,40.668087,2.523095,231.893166,41.463075,50.979587,14.676836,474.419799,2024,9,24
998,998,998,380.592568,47.386266,61.558879,53.934178,4.097152,150.734284,24.851836,91.759379,2.064906,260.247033,2024,9,25
999,999,999,183.942251,155.449796,174.925737,17.814001,3.026831,53.320675,29.860292,19.403229,14.013190,124.227394,2024,9,26

In [24]:
df.drop(['level_0', 'index'], axis=1, inplace=True, errors='ignore')

In [25]:
df

,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI,year,month,day
0,199.994633,108.863806,56.032608,67.924893,2.523095,124.154301,30.930278,13.491951,10.943885,458.517445,2022,1,1
1,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031,2022,1,2
2,295.477637,263.784526,181.719643,26.545854,3.824789,257.818744,39.895783,84.812122,1.888436,367.956930,2022,1,3
3,243.476809,263.784526,53.661509,63.237662,0.854110,108.601272,29.524650,79.009152,13.877300,229.303183,2022,1,4
4,70.847270,407.149351,58.030197,58.031106,0.831322,262.198409,11.288155,41.557842,7.550271,322.416597,2022,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,45.717009,335.338475,173.732673,45.326489,2.523095,208.486255,28.189485,34.584366,7.966478,431.674874,2024,9,22
996,367.752294,479.175018,35.668276,50.086419,0.684967,155.933920,31.681474,28.856730,2.897871,260.247033,2024,9,23
997,63.359266,53.099848,65.408633,40.668087,2.523095,231.893166,41.463075,50.979587,14.676836,474.419799,2024,9,24
998,380.592568,47.386266,61.558879,53.934178,4.097152,150.734284,24.851836,91.759379,2.064906,260.247033,2024,9,25
999,183.942251,155.449796,174.925737,17.814001,3.026831,53.320675,29.860292,19.403229,14.013190,124.227394,2024,9,26

In [5]:
for col in df.select_dtypes(include=np.number).columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df = df[(df[col] >= lower) & (df[col] <= upper)]

In [6]:
df

,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI
1,2022-01-02,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031
7,2022-01-08,347.808697,427.613913,156.458559,3.191364,2.101432,255.788814,7.915938,10.021690,4.231799,297.550297
8,2022-01-09,244.434855,139.840644,17.746401,68.053952,3.430516,62.727119,30.073316,31.711990,10.555893,259.102244
9,2022-01-10,286.148305,254.923983,100.076383,7.079908,0.377734,134.800494,15.127956,28.740863,1.075813,298.177457
16,2022-01-17,128.654475,106.676166,72.731949,73.804507,4.441822,22.034224,10.298826,31.721473,7.361591,69.811860
...,...,...,...,...,...,...,...,...,...,...,...
976,2024-09-03,242.080393,144.462444,168.604479,38.722753,0.704904,24.459442,34.946887,92.955400,5.266817,252.965551
982,2024-09-09,51.573319,239.929706,142.449847,23.983219,3.350222,288.506365,42.392882,71.946370,9.742958,169.760627
984,2024-09-11,293.993615,84.070387,111.553912,82.095921,2.798236,51.487966,38.701380,49.480453,0.665150,437.792222
992,2024-09-19,116.136604,312.908072,112.777880,75.741897,1.774041,143.273263,14.597956,34.661060,5.435580,246.132970
999,2024-09-26,183.942251,155.449796,174.925737,17.814001,3.026831,53.320675,29.860292,19.403229,14.013190,124.227394

In [16]:
def categorize_aqi(aqi):
    if aqi <= 50:
        return "Good"
    elif aqi <= 100:
        return "Satisfactory"
    elif aqi <= 200:
        return "Moderate"
    elif aqi <= 300:
        return "Poor"
    elif aqi <= 400:
        return "Very Poor"
    else:
        return "Severe"

df['AQI_Category'] = df['AQI'].apply(categorize_aqi)

In [17]:
df

,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI,AQI_Category
1,2022-01-02,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031,Poor
7,2022-01-08,347.808697,427.613913,156.458559,3.191364,2.101432,255.788814,7.915938,10.021690,4.231799,297.550297,Poor
8,2022-01-09,244.434855,139.840644,17.746401,68.053952,3.430516,62.727119,30.073316,31.711990,10.555893,259.102244,Poor
9,2022-01-10,286.148305,254.923983,100.076383,7.079908,0.377734,134.800494,15.127956,28.740863,1.075813,298.177457,Poor
16,2022-01-17,128.654475,106.676166,72.731949,73.804507,4.441822,22.034224,10.298826,31.721473,7.361591,69.811860,Satisfactory
...,...,...,...,...,...,...,...,...,...,...,...,...
976,2024-09-03,242.080393,144.462444,168.604479,38.722753,0.704904,24.459442,34.946887,92.955400,5.266817,252.965551,Poor
982,2024-09-09,51.573319,239.929706,142.449847,23.983219,3.350222,288.506365,42.392882,71.946370,9.742958,169.760627,Moderate
984,2024-09-11,293.993615,84.070387,111.553912,82.095921,2.798236,51.487966,38.701380,49.480453,0.665150,437.792222,Severe
992,2024-09-19,116.136604,312.908072,112.777880,75.741897,1.774041,143.273263,14.597956,34.661060,5.435580,246.132970,Poor
999,2024-09-26,183.942251,155.449796,174.925737,17.814001,3.026831,53.320675,29.860292,19.403229,14.013190,124.227394,Moderate

In [18]:
df.columns

Index(['Date', 'PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3', 'Temperature',
       'Humidity', 'WindSpeed', 'AQI', 'AQI_Category'],
      dtype='object')

In [19]:

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['AQI_Category'] = le.fit_transform(df['AQI_Category'])

In [20]:
df

,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI,AQI_Category
1,2022-01-02,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031,2
7,2022-01-08,347.808697,427.613913,156.458559,3.191364,2.101432,255.788814,7.915938,10.021690,4.231799,297.550297,2
8,2022-01-09,244.434855,139.840644,17.746401,68.053952,3.430516,62.727119,30.073316,31.711990,10.555893,259.102244,2
9,2022-01-10,286.148305,254.923983,100.076383,7.079908,0.377734,134.800494,15.127956,28.740863,1.075813,298.177457,2
16,2022-01-17,128.654475,106.676166,72.731949,73.804507,4.441822,22.034224,10.298826,31.721473,7.361591,69.811860,3
...,...,...,...,...,...,...,...,...,...,...,...,...
976,2024-09-03,242.080393,144.462444,168.604479,38.722753,0.704904,24.459442,34.946887,92.955400,5.266817,252.965551,2
982,2024-09-09,51.573319,239.929706,142.449847,23.983219,3.350222,288.506365,42.392882,71.946370,9.742958,169.760627,1
984,2024-09-11,293.993615,84.070387,111.553912,82.095921,2.798236,51.487966,38.701380,49.480453,0.665150,437.792222,4
992,2024-09-19,116.136604,312.908072,112.777880,75.741897,1.774041,143.273263,14.597956,34.661060,5.435580,246.132970,2
999,2024-09-26,183.942251,155.449796,174.925737,17.814001,3.026831,53.320675,29.860292,19.403229,14.013190,124.227394,1

In [32]:
X = df.drop(['AQI_Category', 'Date'], axis=1)
y = df['AQI_Category']

In [33]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

scaler = StandardScaler()

X_standardized = scaler.fit_transform(X)
X_standardized = pd.DataFrame(X_standardized, columns=X.columns)

In [35]:
X

,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI
1,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031
7,347.808697,427.613913,156.458559,3.191364,2.101432,255.788814,7.915938,10.021690,4.231799,297.550297
8,244.434855,139.840644,17.746401,68.053952,3.430516,62.727119,30.073316,31.711990,10.555893,259.102244
9,286.148305,254.923983,100.076383,7.079908,0.377734,134.800494,15.127956,28.740863,1.075813,298.177457
16,128.654475,106.676166,72.731949,73.804507,4.441822,22.034224,10.298826,31.721473,7.361591,69.811860
...,...,...,...,...,...,...,...,...,...,...
976,242.080393,144.462444,168.604479,38.722753,0.704904,24.459442,34.946887,92.955400,5.266817,252.965551
982,51.573319,239.929706,142.449847,23.983219,3.350222,288.506365,42.392882,71.946370,9.742958,169.760627
984,293.993615,84.070387,111.553912,82.095921,2.798236,51.487966,38.701380,49.480453,0.665150,437.792222
992,116.136604,312.908072,112.777880,75.741897,1.774041,143.273263,14.597956,34.661060,5.435580,246.132970
999,183.942251,155.449796,174.925737,17.814001,3.026831,53.320675,29.860292,19.403229,14.013190,124.227394

In [9]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_normalized = scaler.fit_transform(X)

X_normalized = pd.DataFrame(X_normalized, columns=X.columns)